language: java
jdk:
    - oraclejdk8
deploy:
    provider: releases
    api_key: "3727dfc4366e8dabfb3720c442bd193c4710a3f6"
    file: "./target/recipeper-0.1-SNAPSHOT.jar"
    skip_cleanup: true
    on:
        tags: true